FROM jwt-nginx

# Get nginx ready to run
COPY resources/nginx.conf /etc/nginx/nginx.conf
COPY resources/test-jwt-nginx.conf /etc/nginx/test-jwt-nginx.conf
COPY resources/keys /etc/nginx/keys

EXPOSE 8000

STOPSIGNAL SIGTERM

CMD ["nginx", "-g", "daemon off;"]
