#!/usr/bin/env bash

SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"

cd ${SCRIPT_PATH}

# usage: ./build [sX] # With X the step to begin with (default 0)

set -e

# STEP from first arg, defaulting to step 0
STEP=${1:-"s0"}
BRANCH=$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')
BRANCH=${BRANCH:-undefined}

# Copy resources in docker's scope
mkdir -p tmp && cp -r ../config ../test-image ../src tmp

case "$STEP" in
  "s0" )
    echo "Step 0: get base"
    docker build --file Dockerfile.s0 -t jwt-nginx-devel-s0 .
    echo "done step 0"
    ;&
  "s1" )
    echo "Step 1: build module"
    docker build --file Dockerfile.s1 -t jwt-nginx-devel-s1 .
    echo "done step 1"
    ;;
   * )
    echo "Invalid step $STEP"
    exit 1
    ;;
esac

docker tag jwt-nginx-devel-s0 jwt-nginx-devel-s0:$BRANCH
docker tag jwt-nginx-devel-s1 jwt-nginx-devel-s1:$BRANCH

rm -rf tmp
