FROM jwt-nginx-s3

# Cleanup
RUN  apk del .build-deps \
  && apk del .gettext \
  && rm -rf /tmp/*

# Get nginx ready to run
COPY tmp/resources /etc/nginx

# Remove source
RUN rm -fr /usr/local/lib/ngx-http-auth-jwt-module

# Remove archives
RUN rm /usr/local/lib/libjwt.a \
  && rm /usr/lib/libjansson.a

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
  && ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 8000

WORKDIR /etc/nginx

STOPSIGNAL SIGTERM

CMD ["nginx", "-g", "daemon off;"]
#CMD ["nginx-debug", "-g", "daemon off;"]
