FROM jwt-nginx-devel-s0

RUN mkdir -p $JWT_MODULE_PATH/src

ADD tmp/config $JWT_MODULE_PATH/config
ADD tmp/src $JWT_MODULE_PATH/src

RUN cd /usr/src/nginx-$NGINX_VERSION \
  && ./configure --with-compat --add-dynamic-module=$JWT_MODULE_PATH \
  && make modules

ARG LIBJWT=libjwt.so.0.4.0

ADD tmp/test-image/nginx /etc/nginx

RUN mv /usr/src/nginx-1.15.8/objs/ngx_http_auth_jwt_module.so /usr/lib/nginx/modules
RUN mv /usr/local/lib/${LIBJWT} /lib

RUN ln -s /lib/${LIBJWT} /lib/libjwt.so.0
RUN ln -s /lib/${LIBJWT} /lib/libjwt.so
