FROM jwt-nginx-s2

ARG NGINX_VERSION=1.14.0

ARG MODULE_PATH=/usr/lib/nginx/modules

RUN mkdir -p ${MODULE_PATH}

ARG JWT_AUTH_MODULE=ngx_http_auth_jwt_module

ARG JWT_MODULE_PATH=/usr/local/lib/ngx-http-auth-jwt-module

RUN mkdir -p $JWT_MODULE_PATH

ADD tmp $JWT_MODULE_PATH

ENV CONFIG="\
  --prefix=/etc/nginx \
  --sbin-path=/usr/sbin/nginx \
  --modules-path=$MODULE_PATH \
  --conf-path=/etc/nginx/nginx.conf \
  --error-log-path=/var/log/nginx/error.log \
  --http-log-path=/var/log/nginx/access.log \
  --pid-path=/var/run/nginx.pid \
  --lock-path=/var/run/nginx.lock \
  --http-client-body-temp-path=/var/cache/nginx/client_temp \
  --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
  --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
  --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
  --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
  --user=nginx \
  --group=nginx \
  --with-http_ssl_module \
  --with-http_auth_request_module \
  --with-http_stub_status_module \
  --with-http_sub_module \
  --with-threads \
  --with-file-aio \
  --add-dynamic-module=$JWT_MODULE_PATH \
  --with-http_stub_status_module \
  "

RUN cd /usr/src/nginx-$NGINX_VERSION \
      && ./configure $CONFIG --with-debug \
      && make -j$(getconf _NPROCESSORS_ONLN) \
      && mv objs/nginx objs/nginx-debug \
      && mv objs/$JWT_AUTH_MODULE.so objs/$JWT_AUTH_MODULE-debug.so \
      && ./configure $CONFIG \
      && make -j$(getconf _NPROCESSORS_ONLN) \
      && make install \
      && rm -rf /etc/nginx/html/ \
      && mkdir /etc/nginx/conf.d/ \
      && mkdir -p /usr/share/nginx/html/ \
      && install -m644 html/index.html /usr/share/nginx/html/ \
      && install -m644 html/50x.html /usr/share/nginx/html/ \
      && install -m755 objs/nginx-debug /usr/sbin/nginx-debug \
      && install -m755 objs/$JWT_AUTH_MODULE-debug.so /usr/lib/nginx/modules/$JWT_AUTH_MODULE-debug.so \
      && ln -s ../../usr/lib/nginx/modules /etc/nginx/modules \
      && strip /usr/sbin/nginx* \
      && strip /usr/lib/nginx/modules/*.so \
      && rm -rf /usr/src/nginx-$NGINX_VERSION \
      \
      # Bring in gettext so we can get `envsubst`, then throw
      # the rest away. To do this, we need to install `gettext`
      # then move `envsubst` out of the way so `gettext` can
      # be deleted completely, then move `envsubst` back.
      && apk add --no-cache --virtual .gettext gettext \
      && mv /usr/bin/envsubst /tmp/ \
      \
      && runDeps="$( \
        scanelf --needed --nobanner --format '%n#p' /usr/sbin/nginx /usr/lib/nginx/modules/*.so /tmp/envsubst \
          | tr ',' '\n' \
          | sort -u \
          | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
      )" \
      && apk add --no-cache --virtual .nginx-rundeps $runDeps \
      && mv /tmp/envsubst /usr/local/bin/ \
      \
      # forward request and error logs to docker log collector
      && ln -sf /dev/stdout /var/log/nginx/access.log \
      && ln -sf /dev/stderr /var/log/nginx/error.log
