#!/usr/bin/env bash

set -e

dest=headers

image=jwt-nginx-devel-s1

id=$(docker create $image)

echo id:$id

path='/usr/src/nginx-1.15.8/src/'
docker cp $id:$path $dest

path='/usr/local/include/jwt.h'
docker cp $id:$path $dest

docker rm -v $id

touch $dest/ngx_auto_config.h
